### ISSUE TITLE
Add origin in the message arguments

### ISSUE THREAD

**Issue by gdaniel** [xatkit-bot-platform/xatkit-chat-widget#42]
This can be retrieved with `window.location.origin`.

**Comment by gdaniel** [comment]
@hamzaed I tested it with auto-discovery of the bot location, could you check if it works with the constructor property and/or if we need to add a new constructor parameter to specify the origin?

**Comment by hamzaed** [comment]
We just need to expose the parameter in renderXatkitWidget #43

**Comment by hamzaed** [comment]
It's done. We can close this issue now.
