### ISSUE TITLE
Fail to connect to server with autoClear: false

### ISSUE THREAD

**Issue by gdaniel** [xatkit-bot-platform/xatkit-chat-widget#65]
The widget manages to connect the first time we load the page, but cannot do it afterwards. There is probably a mismatch between the conversation id in the local storage and in the server.

**Comment by hamzaed** [comment]
In my case, I receive a fallback message after reloading the page when `autoClear` is set to `true`.  I can confirm that the conversation id used for the `init` event and stored in the local session is the same one received from the server on the `init_confirm` event. I used the last stable version of Xatkit.

**Comment by gdaniel** [comment]
I'll double check and post the steps to reproduce the issue. When this happens I have the message "Trying to connect to the Xatkit server", but the connection never succeeds. But I have to do some exploration on this, I assumed it was this (related to a discussion we had a long time ago about the issues with `autoClear`).

**Comment by hamzaed** [comment]
During my test, the connection succeeds but the context is lost and the fallback message is received. We should investigate why we're not getting the same behavior. I'm interested to learn more about this issue and help solve it. I'll wait for the steps to reproduce it.

**Comment by gdaniel** [comment]
You are right, I tested with the latest version of both the widget and the platform and it works as you say. I assume the issue I got is related to the specific bot I was using, I'll investigate it but it's not related to the widget, my bad! I'll open an issue for the fallback error though.
